vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.root_dir%/../web/uploads/images'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid