easy_admin:
    site_name: 'Blog'

    list:
        actions:
            - { name: 'show', icon: 'search', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'remove', label: '' }
    design:
        brand_color: '#4C0000'
        form_theme: 'vertical'
    entities:
        Product:
            form:
                fields:
                    - 'title'
                    - 'perex'
                    - { property: 'text', type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }
                    - { property: 'imageFile', type: 'file' }
            class: AppBundle\Entity\Product
            list:
                fields:
                    - 'id'
                    - 'title'
                    - 'text'
                    - 'author'
                    - 'updatedAt'
        User:
            class: AppBundle\Entity\User
            label: 'Users'
            password_encoding: { algorithm: 'bcrypt'}
            list:
                title: '%%entity_label%% list'
                fields:
                    - 'id'
                    - 'username'
                    - 'email'
                    - 'roles'
            edit:
                title: '%%entity_label%% list'
                fields:
                    - 'email'
        Comment:
            form:
                fields:
                    - { property: 'content', type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }
            class: AppBundle\Entity\Comment
            list:
                fields:
                    - 'id'
                    - 'content'
                    - 'author'
                    - 'publishedAt'